### ISSUE TITLE
Batch sign PSBTs

### ISSUE THREAD

**Issue by yknl** [secretkeylabs/xverse-web-extension#423]
Add the ability for apps to request signing of multiple PSBTs

**Comment by T1-O** [comment]
@yknl Can multiple PSBT signatures be requested via Sats-Connect?

**Comment by GAD2511** [comment]
Think it's yes
It's enhanced

**Comment by GAD2511** [comment]
Yes

**Comment by yknl** [comment]
> @yknl Can multiple PSBT signatures be requested via Sats-Connect?

Not yet

**Comment by teebszet** [comment]
released in https://github.com/secretkeylabs/xverse-web-extension/releases/tag/v0.24.0
