### ISSUE TITLE
Xverse web extension showing wrongly derived BTC Address.

### ISSUE THREAD

**Issue by ewiraatm** [secretkeylabs/xverse-web-extension#469]
# Component
<img width="706" alt="Screen Shot 2023-06-06 at 9 28 35 AM" src="https://github.com/secretkeylabs/xverse-web-extension/assets/2531197/78fca50d-b873-4baa-bca5-0eddaa6fb0e1">
<img width="350" alt="Screen Shot 2023-06-07 at 9 30 46 PM" src="https://github.com/secretkeylabs/xverse-web-extension/assets/2531197/4766f2e5-b28f-42ba-9508-533ca1470120">

# Severity
- Critical

# Summary
I imported my seed phrase to Xverse wallet 0.11.3 and then found out that the first address showed on my Xverse wallet (3NwY...) is not a BTC address derived from my seedphrase (as attached from the image). A lot of people including me experienced this issue. And if we have already sent the funds to that wrongly derived address, it's stuck there as we couldn't make any transaction from that wallet with message: 400 Axios Error or PBST error can't find pubkey

And then after v0.11.4 update, that first BTC address on our Xverse extension suddenly got changed (to what I presumed what should've been the correct address).  So many people lost access to our funds that was sent to the BTC address that was shown at first (3NwY.. in my case).

People have been complaining on discord with no response from the Xverse team yet. This haven't even been acknowledged  as a bug.

Is it possible to change back to the address that was firstly shown on Xverse and make it possible to do transaction from that wallet? Was it just an address derived using another derivation path? Or was it a completely random BTC address being shown and we will never ever have access to those?

This seems to be intermittent as not everyone experienced this issue, so I don't know exactly how to reproduce this bug. But there has been more than 30 people who reported this issue on discord. 

Please help to look into it as many people are still trying to find disclosure and get our funds back. Thank you!

**Comment by leshemlin** [comment]
this is a critical bug

**Comment by yknl** [comment]
Which browser are you experiencing this on? All reports of this issue so far have been from users loading the extension into unsupported browsers like Kiwi browser.

**Comment by ewiraatm** [comment]
> Which browser are you experiencing this on? All reports of this issue so far have been from users loading the extension into unsupported browsers like Kiwi browser.

I used Google Chrome Extension on Mac OS Big Sur. Macbook Air M1 2020
