### ISSUE TITLE
Seed Phrase Input Security

### ISSUE THREAD

**Issue by GAD2511** [secretkeylabs/xverse-web-extension#499]
Add ‘Show Secret Key’/’Hide Secret Key’ feature for more safety/security while restoring an existing wallet (inputting the seed phrase)
![image](https://github.com/secretkeylabs/xverse-web-extension/assets/62007848/5757fd76-93d9-47c2-8d2f-28be6bd1333f)

**Comment by Devender1703** [comment]
Hi @GAD2511, 

Do we need an eye icon which can be used to hide/unhide the seed phrase just like we have in password. 

I have built the extension, I can help here.

**Comment by GAD2511** [comment]
Hello, I don't think so. In case there is an error in the words, the user can switch to Show mode with the eye symbol.
I think this is to enhance the security/safety of the seed phrase input

**Comment by Devender1703** [comment]
@yknl if this is approved. I want to work on this .

**Comment by yknl** [comment]
This has been implemented and released in https://github.com/secretkeylabs/xverse-web-extension/pull/566
