### ISSUE TITLE
Sats Connect Inscription - Developer fees are ignored

### ISSUE THREAD

**Issue by hans-crypto** [secretkeylabs/xverse-web-extension#596]
# Component
The new inscription feature with:
* Xverse 0.18.0
* sats-connect 1.1.1

# Severity
- `Major (Unable to proceed on a journey)`

# Summary

The fixed 2,000 sats 'inscription fees' have been applied. However, the 'developer fees' are not considered, meaning the developer doesn't earn anything. Prices in USD aren't consistently displayed, but this isn't a major concern for me.

# Reproduce steps
Call the new `createInscription` function from sats-connect  with an `appFee` of 20,000 sats and a valid `appFeeAddress` like my address `bc1qkktajdw9ry59wczt097d7gppjr43sc6vwm03wh`. 
The amount is show in the confirmation screen:

<img width="359" alt="Screenshot 2023-09-12 at 10 57 20" src="https://github.com/secretkeylabs/xverse-web-extension/assets/108269257/94a55431-6983-486f-89f6-3572846af5a2">

# Expected result

My new balance: 89,36 USD - 7,48 USD = 81,88 USD
and a payment to my `appFeeAddress`.

# Actual result

My new balance: 87,12 USD 🤨 
and my `appFeeAddress` has no balance

Payment: https://mempool.space/tx/e1bde80c107e5818c11981381e0f12929ae0f3c044587d1888bd526d92580604
Reveal Transaction ID: https://mempool.space/tx/78fa9d6e9b2b49fbb9f4838e1792dba7c1ec836f22e3206561e2d52759708251

**Comment by victorkirov** [comment]
Thank you for pointing this out. A fix is on the way!

**Comment by hans-crypto** [comment]
Excellent! I was wondering about the "inscription fee" of 2,000 sats. With every inscription, these 2,000 sats go to the same address bc1qu0jfsc5uz47detzry7d3drk5kg56x7cy4eyez8. Is this a provision for Secret Key Labs, or is it a technical requirement? It would be helpful if this could be explained in the UI. I'm sure I won't be the only person curious about this.

By the way, the term "Bitcoin Value" is a bit confusing. It took me some time to realize that it represents the sum of the Total Fees (30,865 sats) and the minimum inscription value (546 sats). It would also be helpful for the end-user to know that the 546 sats are returned to the sender.

**Comment by victorkirov** [comment]
The 2000 sats fees is the Xverse service fee. We turned it off for a few weeks while we are still in the initial introduction phase to make it easier for developers to test, so testing should be a bit easier going forward.

Thanks for the feedback, it's really great and definitely something we will tackle. If you have any other feedback, please send it our way 🙂

**Comment by hans-crypto** [comment]
Charging a fee is absolutely fine, but it should be more transparent. I noticed the extra fee right away. As an end-user, I would pay this relatively small amount, but only if it's well explained. For example, OrdinalsBot refers to its own charge as a "service fee". This created extra confusion for me because in the code, we had two "service fees" (now called appFee). One for Xverse and one for the developer.

Extra Feedback:
As I've already reported to Jan, there should be a method to estimate the full price of an inscription. Adding this feature would be beneficial, as it would allow people to know the costs in advance. As of now, the first time a user receives price information is at the confirmation screen.

**Comment by victorkirov** [comment]
> Charging a fee is absolutely fine, but it should be more transparent. I noticed the extra fee right away. As an end-user, I would pay this relatively small amount, but only if it's well explained. For example, OrdinalsBot refers to its own charge as a "service fee". This created extra confusion for me because in the code, we had two "service fees" (now called appFee). One for Xverse and one for the developer.

Yeah, that was a bit confusing. Do you think the new interface with appFee in code and having "Service Fee" and "Developer fee" on the confirmation screen is clear? Or is there something we should add more explanation for?

> As I've already reported to Jan, there should be a method to estimate the full price of an inscription. Adding this feature would be beneficial, as it would allow people to know the costs in advance. As of now, the first time a user receives price information is at the confirmation screen.

We got that feedback from him, thank you for bringing it up 🙌  That's definitely something that's missing in the current implementation and will be available in the next iteration.

**Comment by hans-crypto** [comment]
> We got that feedback from him, thank you for bringing it up 🙌 That's definitely something that's missing in the current implementation and will be available in the next iteration.

I'm happy to beta-test this again with a RC of the extension for my [cubes app](https://cubes.haushoppe.art/)! 😄 👍

**Comment by victorkirov** [comment]
> Yes, using the terms "Service Fee" and "Developer Fee" would be a big step forward!
> 
> 
> 
> I will give you extra points if you add a text like this, either somewhere in the UI or on a separate page.
> 
> 
> 
> * Service Fee: This fee supports Secret Key Labs and the ongoing development of Xverse.
> 
> * Developer Fee: This fee supports the entity that created this application.
> 
> * Transaction Fees: This fee is necessary for the actual inscription process. It incentivizes miners (and their operators) to confirm the transaction.
> 
> * Total Fees: This is the final amount the inscription will cost you. It's the Bitcoin value minus 546 sats.
> 
> * Bitcoin Value: This represents the total you'll pay to start the transaction. You'll get back 546 sats, with the first satoshi of this amount associated with your inscription.
> 
> 
> 
> Nerds like me care about stuff like this. At least for me, you can't overcommunicate here. 🤓 

Haha! Yeah, that would make it very clear what everything is. Maybe it's time to bring out the hoverable info icons 😉 I'll send this through to the design team and let you know when it's ready for testing 🙌
