### ISSUE TITLE
Signet support for testing

### ISSUE THREAD

**Issue by mmikrut** [secretkeylabs/xverse-web-extension#828]
Hello,

Newbie here :)

Would it be possible to add support for Signet for testing purposes? Currently, Testnet mining fees are at 262 sat/vB. Additionally, it's challenging to obtain larger volumes of Testnet BTC from existing faucets, making it almost impossible to test inscriptions due to the high fees.

Signet mining fees, on the other hand, are only 1 sat/vB.

Thank you!

**Comment by Yihen-Liu** [comment]
I have update xverse wallet from v-0.36.2 to v-0.37, when I set up the signet BTC URL and FallBack BTC URL to myself signet and mempool.space, which were setup in my local network, it shows that "INVALID URL", can you explain why and how to setup?

**Comment by victorkirov** [comment]
Hi

Signet support was added in the last release. You should be able to switch from settings>network. 

For the custom URL, we check one of the known signet APIs for the block hash of the first block in the API you're setting and compare it to a known correct one. If they don't match, then the URL is rejected.

**Comment by Yihen-Liu** [comment]
@victorkirov  which one provides the API service? bitcoind or electrumX or other ?

**Comment by victorkirov** [comment]
@Yihen-Liu it's an electrs API
https://github.com/Blockstream/electrs
or
https://github.com/mempool/electrs

**Comment by Yihen-Liu** [comment]
> @Yihen-Liu it's an electrs API https://github.com/Blockstream/electrs or https://github.com/mempool/electrs

It does not work. disappointment...

  It is better for xverse wallet team  write document clearly about how to setup electrs server and how to set BTC URL.

Good Luck.
